### PR TITLE
Avoid "Greeter was not compiled with docs" error

### PR DESCRIPTION
**Pull request by MaciejReimann**
### Problem description: 

Compiling `greeter.ex` with `c("greeter.ex")` and then calling `h Greeter` gives  `Greeter was not compiled with docs` error.

### Problem solution: 

Passing  "." as the second  argument to the compiler actually allows to access module's docs with `h Greeter`.

Similar problem and its solution are well described here: [Elixir — Module was not compiled with docs
](https://stackoverflow.com/questions/42504226/elixir-module-was-not-compiled-with-docs)

### CODE REVIEW

**Comment by doomspork** [comment]
Hello @MaciejReimann! I apologize for missing this PR. I think this is a good change. Would you be willing to update the translations with this change? If you're not able to I can take care of that :grin:

**Comment by MaciejReimann** [comment]
> Hello @MaciejReimann! I apologize for missing this PR. I think this is a good change. Would you be willing to update the translations with this change? If you're not able to I can take care of that 😁

Hello @doomspork! Now I apologize for a late reaction. I think it's done though.

**Review by julienXX — APPROVED** [review]

**Review by marocchino — APPROVED** [review]

**Review by vbrazo — APPROVED** [review]
LGTM

**Review by yosangwon — APPROVED** [review]

**Comment by MaciejReimann** [comment]
Hi, @doomspork. Do we need to wait for more approves to merge this PR?

**Comment by marocchino** [comment]
I think Its enough to merge. GTG.

**Comment by MaciejReimann** [comment]
Yay! Thanks :)

**Pull request merged**
