### PR TITLE
[KO] Update basics/basics 1.1.0 -> 1.1.2

### PR DESCRIPTION
**Pull request by riseshia**
## Ref

- 1.1.0 -> 1.1.1 #1143
- 1.1.1 -> 1.1.2 #1184

cc @devleoper @doomspork

### CODE REVIEW

**Comment by riseshia** [comment]
Question to @doomspork,
Currently, I can not merge my own pull request, but only from others. Is it intended permission? ;)

**Comment by riseshia** [comment]
> You need at least one 👍 review from other folks to merge it and it looks like now you can merge it :shipit:

actually, that's the point... korean is better case, but  japanese is not the case. ;_; anyway Thanks to approve!

**Comment by doomspork** [comment]
@riseshia it's unfortunately a limitation of all of the different permissions of GitHub.  To keep master locked and require a review, GitHub won't allow a person to merge their own PRs.  It's not ideal but we've previously had a handful instances where malformed markdown in a PR took the site offline so this "roadblock" forces a second pair of eyes on the PR.

If you @ me in the future I'll get things merged for you ❤️ 

Sorry for the trouble but thanks for all of your hard work 😁

**Comment by riseshia** [comment]
🙆‍♂️

**Pull request merged**
