### PR TITLE
Create redirect pages for old location of English lessons

### LINKED ISSUE #1397: Deal with redirect_from directive in a better way
When we decided to move English language lessons from https://elixirschool.com/lessons/ to https://elixirschool.com/en/lessons/
we added the `redirect_from` directive to every lesson. 
for example
`en/lessons/advanced/typespec/` has this frontmatter:
```
---
version: 1.0.2
title: Specifications and types
redirect_from:
  - /lessons/advanced/typespec/
---
```

the problem with this is that when people translate the page, they leave that as it is, and there is one URL that redirects to two different language versions, so the old link is randomly taken over. 

My suggestion for the time being is:
1. add a warning in the README file to remove every occurrence of redirect_from
2. remember when reviewing the lessons added, that it cannot contain a redirect_from (I just approved one today and totally overlooked ay this)
3. add a comment before the redirect_from directive asking translators to remove it, such as this for example:

```
---
version: 1.0.2
title: Specifications and types
# PLEASE remove the `redirect_from` directive below if you are translating this lesson
redirect_from:
  - /lessons/advanced/typespec/
---
```

/cc @elixirschool/developers

### PR DESCRIPTION
**Pull request by eksperimental**
It creates a .md file with the "redirect_to" directive for every lesson,
in order to avoid translators to copy the "redirect_from" directive

Closes #1397

Script for creating the new redirect files

```bash
for d in $( ls -1 en/lessons/ ); do
  mkdir -p lessons/${d}
  for f in $( ls -1 en/lessons/${d}/ | sed -e 's/\..*$//' ); do
    echo -e "---\nredirect_to:\n  - /en/lessons/${d}/${f}/\n---" > lessons/${d}/${f}.md;
  done
done
```

### CODE REVIEW

**Comment by eksperimental** [comment]
Can anybody please test it locally, as I cannot do it for the time being in my computer.
/cc @elixirschool/developers @elixirschool/english

**Comment by doomspork** [comment]
@eksperimental I get an error trying to run these changes:

```shell
➜  elixir-school git:(move_redirect_from_english) ✗ be jekyll s --verbose
Ignoring bindex-0.5.0 because its extensions are not built.  Try: gem pristine bindex --version 0.5.0
  Logging at level: debug
Configuration file: /Users/sean/Projects/elixirschool/elixir-school/_config.yml
  Logging at level: debug
         Requiring: /Users/sean/Projects/elixirschool/elixir-school/_plugins/elixir_school.rb
         Requiring: jekyll-assets
ExecJS, JS Runtime or `less' not available. Skipping the loading of libraries.
         Requiring: jekyll-redirect-from
         Requiring: jekyll-sitemap
         Requiring: kramdown
         Requiring: uglifier
            Source: /Users/sean/Projects/elixirschool/elixir-school
       Destination: /Users/sean/Projects/elixirschool/elixir-school/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Creating a new instance of:  Jekyll::Assets::Env
The old value of Sprockets:
       EntryFilter: excluded /LICENSE
       EntryFilter: excluded /GLOSSARY.md
       EntryFilter: excluded /config.ru
       EntryFilter: excluded /README.md
       EntryFilter: excluded /Rakefile
       EntryFilter: excluded /CONTRIBUTING.md
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
       EntryFilter: excluded /Procfile
           Reading: _posts/2018-04-03-a-look-at-16.md
           Reading: _posts/2018-04-23-just-the-beginning.md
jekyll 3.7.3 | Error:  undefined method `[]' for nil:NilClass
```

**Comment by eksperimental** [comment]
what does that mean? if it doesn't work it will have to wait until i manage update the software needed to run it locally

**Comment by nscyclone** [comment]
Thanks @eksperimental! Everything works great locally with a couple of small fixes, please take a look at #1420.

**Comment by doomspork** [comment]
Closing this in favor of #1420 since it has these commits 👍

**Pull request closed without merging**
