### PR TITLE
OTP Supervisors: Make correction mentioning 0 as a valid time out + Fix Lists Indentation

### PR DESCRIPTION
**Pull request by eksperimental**
Timeout could be `0`.

### CODE REVIEW

**Comment by eksperimental** [comment]
Additionally it fixes the list indentation.
I think you should review your guides if you are using this style.

-----------

This is how it looks now,
image

-----------
This is how it looks after the PR

image

**Comment by eksperimental** [comment]
I just found out that shutdown value of `0` is only valid on OPT 24.

**Review by kinson — APPROVED** [review]
Thanks for the correction and formatting update 🚀 !

**Comment by eksperimental** [comment]
Do we want to leave 0 as a valid value, since it's only available since OTP 24 and OTP 20-23 are currently supported by the supported versions of Elixir.

**Comment by kinson** [comment]
If you want to open a pr to add a note about that compatibility concern that would be great! Do you mind sharing the reference you are using?

Thanks again for helping out 🚀

**Comment by eksperimental** [comment]
https://github.com/elixir-lang/elixir/pull/11836

Apparently the spec included `0`, but in reality that would not work.
Anyway, the Elixir specs don't include `0` and will not include it until OTP 24 is supported exclusively, so maybe the PR should remove the `0` for the time being.

**Pull request merged**
