### PR TITLE
[PT] Update GenStage lesson

### PR DESCRIPTION
**Pull request by guilhermelazzari**
This change updates the Portuguese translation of GenStage lesson, formatting the code with the Elixir format tool. Now it's in sync with the English one.

### CODE REVIEW

**Comment by doomspork** [comment]
@guilhermelazzari I'm sorry for the hiccup, #1253 was merged and now there is a conflict.  Could you resolve that for us?  Thank you kindly!

**Comment by pragmaticivan** [comment]
This PR ended up with 0 files changed. Should we close?

**Comment by guilhermelazzari** [comment]
I think so. Sorry, I was not aware of #1253. Apparently, it fixed all
languages to the new format.

**Comment by pragmaticivan** [comment]
Thanks @guilhermelazzari ! :)

**Pull request closed without merging**
