### PR TITLE
Create redirect pages for old location of English lessons

### LINKED ISSUE #1397: Deal with redirect_from directive in a better way
When we decided to move English language lessons from https://elixirschool.com/lessons/ to https://elixirschool.com/en/lessons/
we added the `redirect_from` directive to every lesson. 
for example
`en/lessons/advanced/typespec/` has this frontmatter:
```
---
version: 1.0.2
title: Specifications and types
redirect_from:
  - /lessons/advanced/typespec/
---
```

the problem with this is that when people translate the page, they leave that as it is, and there is one URL that redirects to two different language versions, so the old link is randomly taken over. 

My suggestion for the time being is:
1. add a warning in the README file to remove every occurrence of redirect_from
2. remember when reviewing the lessons added, that it cannot contain a redirect_from (I just approved one today and totally overlooked ay this)
3. add a comment before the redirect_from directive asking translators to remove it, such as this for example:

```
---
version: 1.0.2
title: Specifications and types
# PLEASE remove the `redirect_from` directive below if you are translating this lesson
redirect_from:
  - /lessons/advanced/typespec/
---
```

/cc @elixirschool/developers

### PR DESCRIPTION
**Pull request by nscyclone**
Closes #1397.

### CODE REVIEW

**Comment by eksperimental** [comment]
Thank you@nscyclone 
One thing i have noticed is that redirect_to can only take one item so it shouldnt be a list but all in one line

**Comment by doomspork** [comment]
This is probably a stretch but with a plugin is it possible to generate this content _without_ creating the `lessons` folder?

**Comment by eksperimental** [comment]
I wasnt able to find one

**Comment by doomspork** [comment]
I think with a YAML like this, it might not be too bad:

```yaml
- dir: /
  files:
    - index

- dir: /lessons/basics/
  files:
    - basics
    - collections
    - enum
    - pattern-matching
    - control-structures
    - functions
    - pipe-operator
    - modules
    - mix
    - sigils
    - documentation
    - testing
    - comprehensions
    - strings
    - mix-tasks
    - iex-helpers

- dir: /lessons/advanced/
  files:
    - erlang
    - error-handling
    - escripts
    - concurrency
    - otp-concurrency
    - otp-supervisors
    - metaprogramming
    - umbrella-projects
    - typespec
    - behaviours
    - gen-stage
    - protocols

- dir: /lessons/specifics/
  files:
    - plug
    - ecto
    - eex
    - ets
    - mnesia
    - debugging

- dir: /lessons/libraries/
  files:
    - guardian
    - poolboy
    - benchee
    - bypass
```

```ruby
module ElixirSchoolRedirects
  class RedirectPage < Jekyll::Page
    def initialize(site, dir, name)
      @base = site.source
      @dir = dir
      @name = "#{name}.md"
      @site = site

      process(@name)

      self.content = ""
      self.data = {'redirect_to' => "/en/#{dir}/#{name}"}
    end
  end

  class Generator < Jekyll::Generator
    def generate(site)
      site.data['redirects'].each do |redirect|
        redirect['files'].each do |file|
          site.pages << RedirectPage.new(site, redirect['dir'], file)
        end
      end
    end
  end
end
```

**Comment by eksperimental** [comment]
looks great!
can you extend it to work with the other languages that were moved: `jp`, `my`
and it will be `cn`, and `tw` in the future

**Comment by eksperimental** [comment]
looks great!
can you extend it to work with the other languages that were moved: `jp`, `my`
and it will be `cn`, and `tw` in the future

**Comment by eksperimental** [comment]
if you are extending it, you may want to read the contents from https://github.com/elixirschool/elixirschool/blob/master/_data/contents.yml

**Comment by doomspork** [comment]
I'll give that a whirl @eksperimental 👍

**Comment by doomspork** [comment]
Closing in favor of #1423

**Pull request closed without merging**
