### PR TITLE
Improve GenServer definition to state that it's single process

### PR DESCRIPTION
**Pull request by brain-geek**
Okay, this may be discussable overall, but this may be improvement.

#487 is a source where I took the idea from, and it makes some sense.

Let's discuss if you think that it's a bad change. :)

### CODE REVIEW

**Comment by pjhampton** [comment]
Slightly unrelated, but I think we should split out the OTP lessons into their own section. Talk with various ex devs it seems that OTP is pretty difficult to grasp for many

**Comment by doomspork** [comment]
@pjhampton so: Basics, Advanced, Specifics, OTP?

I'm all for better organization or lessons.  It might help us see areas we should elaborate on.

**Comment by pjhampton** [comment]
yeah @doomspork 

I think this because when I look around nobody (except seasoned / advanced) guys are making use of this stuff. I think it's fair to assume that OTP is harder to learn / understand and requires it's own dedicated area where people can spend time in.

Thoughts @elixirschool/developers ?

**Comment by doomspork** [comment]
I could get behind that.  Think you and I could identify and tackle lessons for the other parts of OTP we haven't covered?

**Comment by pjhampton** [comment]
Yeah, just to add another footnote here - I think we're good at explaining the _what_ and _how_, but not the _why_ or _when_. I think we should:

1. Have a dedicated section for OTP
2. Have a simple and a difficult example
3. Explain good use cases
4. Advise on spotting OTP opportunities

As for identifying - yeah, I am up for that. As for writing lessons, my time isn't going to free up until next weekend which sucks and I'm still finishing the ExUnit lesson :(

**Comment by doomspork** [comment]
@pjhampton once #1423 is merged we can make some changes to it to support these changes (redirecting old links to the new otp section) and start on this 👍

**Pull request merged**
