### PR TITLE
Update nimble_publisher.md to be compatible with Phoenix 1.7 

### PR DESCRIPTION
**Pull request by yellowsman**
Update nimble_publisher.md to be compatible with Phoenix 1.7

For the current lesson, the version of the Phoenix library has been updated, so if you try to follow it as is, you will get an error.

This PR adapts NimblePublisher lessons to Phoenix 1.7

### CODE REVIEW

**Comment by yellowsman** [comment]
This PR modified source code ;-)
https://github.com/yellowsman/nimble_school_transcribing

**Comment by doomspork** [comment]
@yellowsman this is great! Would you be so kind as to update the version at the top of the file so it will trigger notifications for translation?

**Comment by yellowsman** [comment]
@doomspork 
Thanks! 

> Would you be so kind as to update the version at the top of the file so it will trigger notifications for translation?
Is the updated version "1.1.02 or "1.0.3"?

**Comment by doomspork** [comment]
@yellowsman `1.1.0` should do the trick!

Thank you

**Comment by yellowsman** [comment]
@doomspork 
I updated the version to `1.1.0`.
Thank you for the review!

**Review by doomspork — APPROVED** [review]

**Comment by doomspork** [comment]
Thank you @yellowsman!

**Comment by yellowsman** [comment]
@doomspork 
Thank you for merging this PR!
I will continue to support you!

**Pull request merged**
