### PR TITLE
[GR] brings greek mnesia lesson up to date

### PR DESCRIPTION
**Pull request by gemantzu**
Also fixes some new lines in the original lesson

### CODE REVIEW

**Comment by doomspork** [comment]
@gemantzu we need to get you some more @elixirschool/greek peeps!

**Comment by gemantzu** [comment]
Yup! @Kosmas we need your help!

**Comment by Kosmas** [comment]
@gemantzu starting this weekend again :-)

**Comment by gemantzu** [comment]
:) Thank you!

**Pull request merged**
