### PR TITLE
[PT] Update basic testing to version 1.1.1

### PR DESCRIPTION
**Pull request by renatosuero**
Update basic for testing #1295

### CODE REVIEW

**Comment by renatosuero** [comment]
thanks @brunoliveira8  =)

**Comment by brunoliveira8** [comment]
You are welcome :) The Test Setup sample still the old example.

**Comment by brunoliveira8** [comment]
I am not sure, but what do you think is better:
1. ExUnit.CaptureLog é o equivalente para capturar saída **para** Logger.
2. ExUnit.CaptureLog é o equivalente para capturar saída **de** Logger.

**Comment by renatosuero** [comment]
@brunoliveira8  thanks, I think that the option 2 is better.

**Pull request merged**
