### PR TITLE
Update all Poolboy lessons to the latest

### PR DESCRIPTION
**Pull request by doomspork**
I went ahead and applied https://github.com/elixirschool/elixirschool/pull/2176 to all of the available lessons. I also changed the version from 1.1.3 to 1.2.0 since this was more than just a language specific tweak.

### CODE REVIEW

**Comment by doomspork** [comment]
I don't know this needs to wait for :100: approval across all touched languages. If it's good to approve, please merge :+1:

**Comment by doomspork** [comment]
Thank you @erickgnavar! I hope you are well these days :grin:

**Comment by riseshia** [comment]
👍

**Comment by marocchino** [comment]
ko version number was not updated from `1.1.1`. 🙈

**Comment by doomspork** [comment]
@marocchino I will take care of that, my apologizes!

**Pull request merged**
