### PR TITLE
New lesson on NimblePublisher

### PR DESCRIPTION
**Pull request by jaimeiniesta**
Hello! As we talked in https://twitter.com/elixirschool/status/1321551269304049664 here's a new lesson on how to use NimblePublisher.

I can also provide a Spanish translation later on.

### CODE REVIEW

**Comment by doomspork** [comment]
Woooohooo! Thank you and welcome @jaimeiniesta!! This is really great. Very excited to be adding more library coverage, especially the Nimble* collection.  

As I mentioned in the tweet, I'd really like to eventually move Elixir School off Jekyll and to Phoenix, it's something folks have wanted to do for awhile since an Elixir app serves as both an example and enables us to do a richer things.

**Comment by jaimeiniesta** [comment]
Hey that's great @doomspork !

I'll be happy to contribute with the migration to Elixir. Let me think about it and I'll come up with a proposal.

In the meantime, after this PR is approved, I'll provide a Spanish translation, I think a separate PR would be better for this.

**Comment by doomspork** [comment]
@jaimeiniesta one of our previous threads on the topic (before NimblePublisher existed though): https://github.com/elixirschool/elixirschool/issues/523

**Review by doomspork — DISMISSED** [review]
This is a _great_ addition @jaimeiniesta! I'll get a tweet out about this as soon as it deploys :tada:

**Review by doomspork — APPROVED** [review]

**Pull request merged**
