### PR TITLE
Add GitHub star button

### PR DESCRIPTION
**Pull request by lex111**
image

Do you think is it better to hide the counter?

### CODE REVIEW

**Comment by doomspork** [comment]
@lex111 I think the star count is fine. It may help folks notice the addition too. 

Wonderful series of improvements, I'm so grateful ❤️

**Comment by doomspork** [comment]
@lex111 since you're clearly interested in helping with more than the translations, I'll add you to the @elixirschool/developers team as well. We really appreciate all you've done 😁

**Comment by lex111** [comment]
It would be cool if the ElixirSchool work on an Elixir-based site generator, rather than on Jekyll. I was... I was thinking aloud :smiley:

**Comment by doomspork** [comment]
@lex111 we've talked about this. Unfortunately, the existing Elixir static site generators are not supported and would require a fair amount of work to get to the point that we could swap them in for Jekyll.

We've also kicked around the idea of using Phoenix and handling the generation of pages from the markdown, something akin to https://github.com/thoughtbot/high_voltage

**Comment by lex111** [comment]
Yeah, I understand it all, It'd be  very cool :heart_eyes:

**Pull request merged**
