### PR TITLE
[JA] Translate lessons/basic/strings

### PR DESCRIPTION
**Pull request by starfish719**
I translated `lessons/basics/strings` section!
Please review! @elixirschool/japanese

refs: https://github.com/elixirschool/elixirschool/pull/1535

### CODE REVIEW

**Comment by marocchino** [comment]
@riseshia Would you like to invite @starfish719  to the Japanese team?

**Comment by riseshia** [comment]
LGTM! @doomspork, could you invite @starfish719 to @elixirschool/japanese ?

**Comment by starfish719** [comment]
@marocchino Thank you for your review 👍

**Comment by doomspork** [comment]
@riseshia most certainly! Thank you for all your help @starfish719 and welcome 😁 

We have a Slack you can join if you'd like: http://admissions.elixirschool.com

**Comment by starfish719** [comment]
@doomspork Thank you for invite.
I joined organization and slack.

**Pull request merged**
