### PR TITLE
Update mix.exs file snippet for newly created projects

### PR DESCRIPTION
**Pull request by crabonature**
.

### CODE REVIEW

**Comment by doomspork** [comment]
@crabonature you are on a roll, this is _great_ work!  Do you have a twitter handle?

**Comment by crabonature** [comment]
@doomspork. Nope don't have a twitter handle. Should I?

**Comment by doomspork** [comment]
@crabonature nope, just curious!  If someone does have a Twitter account I like to give them credit for their contributions 😁

**Comment by crabonature** [comment]
@doomspork  Ah, now I know it can be handy. 😄

**Pull request merged**
