### PR TITLE
[BG] Fixes and updates to basics & collections lessons

### PR DESCRIPTION
**Pull request by svileng**
Spelling mistake fixes and minor grammar updates here and there.

I've compared the BG and EN version of `basics/basics.md`, and the BG one was already up-to-date with the English version, so I'm not sure what content was added/modified in the `1.x.x` English version 🤔  Anyway, it's up-to-date and should be fine 👍 

Also small update to `basics/collections.md` to bring it up to `1.1.2`.

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @merkata!

**Comment by merkata** [comment]
Hi @doomspork, I believe there is not a designated translator for BG, but seeing there is some interest, I might as well pick up translating again, it was fun. Also hi @svileng, small world :smile:

**Comment by svileng** [comment]
👋 😄

**Comment by doomspork** [comment]
@merkata & @svileng if you'd be interested in helping with the translations I'd gladly make a team for you both 😁

**Comment by svileng** [comment]
@doomspork I'd be happy to occasionally update/proof-read/review content, but my technical vocabulary in Bulgarian is quite limited, so I probably won't attempt translating content from scratch 😅Then there's the issue of time and the Ecto content waiting to be written... 😆

**Pull request merged**
