### PR TITLE
[fr] Update basics.enum lesson to 1.4.0

### PR DESCRIPTION
**Pull request by dabielf**

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @dabielf!  I'll give the @elixirschool/french team a chance to comment before I merge.

**Comment by dabielf** [comment]
My pleasure @doomspork , I have a few weeks before me, want to perfect my skills in Elixir, and what better way than to translate a whole course :)

**Comment by dabielf** [comment]
@doomspork what about #1502 , #1503 and #1504  ? Is there any prblem with them ?

**Comment by doomspork** [comment]
Thank you for calling those to my attention @dabielf!  My apologizes

**Pull request merged**
