### PR TITLE
feat/fr_comprehensions

### PR DESCRIPTION
**Pull request by TGITS**
A french translation proposal for the lesson about comprehensions.

### CODE REVIEW

**Review by doomspork — APPROVED** [review]

**Comment by doomspork** [comment]
Thank you @TGITS! Apologizes for the delay getting these merged.

**Comment by TGITS** [comment]
No problem @doomspork :-)

**Comment by doomspork** [comment]
Thanks for understanding @TGITS! I hope you are well :grin:

**Comment by TGITS** [comment]
I'm fine thanks :-). I hope you are well as well :-D

**Pull request merged**
