### PR TITLE
[JA] misscording at the comprehensions lesson #1394

### PR DESCRIPTION
**Pull request by gimKondo**

### CODE REVIEW

**Comment by riseshia** [comment]
Thanks to PR!!! Could you resolve conflict? @gimKondo

**Comment by gimKondo** [comment]
@riseshia Sorry, I forgot to track upstream. I'll do it soon.

**Comment by gimKondo** [comment]
@riseshia OK, that's finished.

**Comment by riseshia** [comment]
:tada:

**Pull request merged**
