### PR TITLE
Update Nerves section to reflect recent updates

### PR DESCRIPTION
**Pull request by fhunleth**
* Update output text to match what you currently seen when making a new
  Nerves project
* Update networking configuration and links to refer to `vintage_net`.
  The `vintage_net` library replaced `nerves_networking` earlier this
  year.
* Update `nerves_init_gadget` references and links to `nerves_pack`
  which is used by default now
* Link to the `vintage_net` cookbook for additional help with network
  configuration.
* Update reference to `nerves_firmware_ssh` to `ssh_subsystem_fwup`
  which replaced `nerves_firmware_ssh` as the default

### CODE REVIEW

**Review by mmmries — APPROVED** [review]
This looks great. Having the up-to-date info on vintage_net and how to set up networking will help a lot of new people have a good first experience.

**Comment by mmmries** [comment]
@SophieDeBenedetto this looks like a great improvement to the project. Any idea who I should tag here to get a review?

**Comment by SophieDeBenedetto** [comment]
Thanks for the ping @mmmries! Taking a look now 😄

**Review by SophieDeBenedetto — APPROVED** [review]

**Comment by SophieDeBenedetto** [comment]
Thanks for the updates @fhunleth! Merging this now and will shoot off a tweet today to draw some attention to the changes 🚀

**Comment by fhunleth** [comment]
@SophieDeBenedetto and @mmmries Thanks for reviewing and merging the PR! I'm a late comer to Elixir School, but the content here is great. I was super excited to see the Nerves section. I hope to add more or work with others to add more to it. Thanks!!

**Comment by SophieDeBenedetto** [comment]
> @SophieDeBenedetto and @mmmries Thanks for reviewing and merging the PR! I'm a late comer to Elixir School, but the content here is great. I was super excited to see the Nerves section. I hope to add more or work with others to add more to it. Thanks!!

Would love to see any Nerves contributions!

**Comment by gemantzu** [comment]
Thanks @fhunleth ! I love your project and am looking forward to seeing more content from you!

**Pull request merged**
