### PR TITLE
[AR] Translate index page and Update basics/basics lesson

### PR DESCRIPTION
**Pull request by abublihi**
Translate index page (was not in _arabic_)
Fix and update basics/basics lesson

### CODE REVIEW

**Comment by abublihi** [comment]
Okay, no problem :+1:

**Comment by doomspork** [comment]
Thank you for understanding @abublihi!  I hope you've had a wonderful weekend 😁

**Comment by abublihi** [comment]
Done

**Comment by abublihi** [comment]
Done.

**Comment by abublihi** [comment]
@doomspork please review the pull request.

**Comment by doomspork** [comment]
Thank you @abublihi and @ibrsalnuqaydan, I very much appreciate your involvement!  I hope we'll see more of y'all 😁

**Pull request merged**
