### PR TITLE
reordered `alias` introduction and corrected`as:`

### PR DESCRIPTION
**Pull request by TwistingTwists**
IMHO, introducing *without alias* code first to a beginner followed by *with alias* helps understand the difference more easily.
Also, `as:` keyword was wrongly mentioned in the doc. So fixed that. 
So, edited the modules.md accordingly.

### CODE REVIEW

**Comment by doomspork** [comment]
What timing @tajchumber! This needs to be bumped to `1.5.0`, not just `1.4.1` since it's a change we want reflected in the translations.

**Comment by tajchumber** [comment]
I was thinking `1.4.1` but wrote `1.5.0` :/

**Comment by TwistingTwists** [comment]
@doomspork : How do I bump the version? I can't seem to find it anywhere. Please point me to some link, or a way to do the same.

**Comment by tajchumber** [comment]
@TwistingTwists at the very top of the file you have
```
---
version: 1.4.0
title: Modules
---
```

just change the value of `1.4.0` to `1.4.1`

**Comment by TwistingTwists** [comment]
@tajchumber 
https://github.com/TwistingTwists/elixirschool/pull/1/commits/ebccc1d93dabfae2b6977717948be7438fc22beb

Did the same here.

**Comment by doomspork** [comment]
@TwistingTwists can you make the change to the version on this branch (and PR)? It looks like you created a new branch with the version change:

image

**Comment by doomspork** [comment]
@TwistingTwists I'm not sure what's happened but now your changes are gone and have been replaced by just the version change 😰

**Comment by doomspork** [comment]
I'm going to close this PR for now. @TwistingTwists if you're interested in contributing we'd love to have your changes but I think something has gone wrong with this branch. Perhaps a new branch would resolve the problem?

**Pull request closed without merging**
