### PR TITLE
[PT] Translation: specifics/ecto

### PR DESCRIPTION
**Pull request by thiamsantos**
Update specifics/ecto portuguese translation.

### CODE REVIEW

**Comment by notactuallypagemcconnell** [comment]
This looks great! If you have someone in mind to review feel free, else 👍 this comment and I will merge after you do so :)

**Comment by thiamsantos** [comment]
@pragmaticivan can you take a look?

**Comment by doomspork** [comment]
@thiamsantos I've added the @elixirschool/portuguese team as reviewers, if no one is available to review I can merge in the next few days.

We really appreciate all of your help with these translations.  Would you be open to joining our organization?  People like you are what has made Elixir School so great 😁

**Comment by notactuallypagemcconnell** [comment]
@doomspork +1 didnt realize we had those groups - will use in future translation pings. Thanks!

**Comment by thiamsantos** [comment]
@doomspork thanks! I would be happy to join the organization.

**Comment by anderkonzen** [comment]
Thanks @thiamsantos !

**Pull request merged**
