### PR TITLE
[PT] Update lesson Specifics/Nerves -> 1.1.2

### PR DESCRIPTION
**Pull request by g-belmonte**
Closes https://github.com/elixirschool/elixirschool/issues/2600

### CODE REVIEW

**Comment by thiamsantos** [comment]
@g-belmonte Looking at the diff `git diff 8271d1c64fb5bd1a3487e9c902c52fede061c7ea HEAD en/lessons/specifics/nerves.md` seems that we had a couple more changes to this new version.

image

Would you be able to also take a look in those?

**Comment by g-belmonte** [comment]
@thiamsantos Thanks, I found 2 things I had looked over the first time. I've double checked now and it should be ready to go :)
If you spot anything else, just let me know.

**Review by thiamsantos — APPROVED** [review]

**Comment by thiamsantos** [comment]
Thanks @g-belmonte :purple_heart:

**Comment by g-belmonte** [comment]
My pleasure! @thiamsantos

**Pull request merged**
