### PR TITLE
fix acronym

### PR DESCRIPTION
**Pull request by rutaka-n**
diaLyzer. not diayzer =)

### CODE REVIEW

**Comment by doomspork** [comment]
Thank and welcome @rutaka-n!

**Comment by eksperimental** [comment]
Please bump version, and update translated versions if they share the same version, if not leave the version as is regardless the change.

**Comment by doomspork** [comment]
@eksperimental why?  If the change has been applied to all the languages why bother with a version bump?

**Comment by eksperimental** [comment]
It is not good practice. If you changed something, its better to update the version, even if its trivial as this. Greek version didnt get updated by the way.
What happens if somebody started translating that same version. They will never know there was a change introduced.
The one exception to this rule would be not to bumo the version is there is a stylistic change or a spelling mistake that doesn't get translated/carried over to other languages

**Comment by gemantzu** [comment]
Ow I figured that it was ok in the other translations, if it is not by all means go ahead and bump the version!

**Pull request merged**
