### PR TITLE
[JA] Bump up basics/testing to 1.1.2

### PR DESCRIPTION
**Pull request by ueneid**
Hi all, this is a tiny patch to improve Japanese documentation. Could you review this?

### CODE REVIEW

**Comment by riseshia** [comment]
🙈Thanks to pull request!
LGTM to me, but you don't need to bump up version. that version is for following raw lessions(en).
Could you revert that change?

**Comment by ueneid** [comment]
Oh, got it. I'll revert it soon.

**Comment by ueneid** [comment]
@riseshia I reverted 0464a03 and re-committed with the new change. If it's better to create another PR to clean up commits, plz let me know. I'll do it 😄

**Comment by riseshia** [comment]
Thanks! XD

**Pull request merged**
