### PR TITLE
[zh-hant] Update all Traditional Chinese Translation to latest Version

### PR DESCRIPTION
**Pull request by lithiumpie**
basics/collections v1.2.3
basics/enum v1.4.0
basics/pattern-matching v1.0.2
basics/control-structures v1.1.1
basics/functions v1.1.0
basics/pipe-operator v1.0.1
basics/modules v1.2.0
basics/mix-tasks v1.0.2

advanced/otp-concurrency v1.0.3
advanced/otp-supervisors v1.1.1

specifics/plug v1.2.0
specifics/ecto v1.3.0

### CODE REVIEW

**Comment by lithiumpie** [comment]
I don't know why this PR includes my last commit. But I check the files change, it's only patch with commits this time. :confused:

**Comment by doomspork** [comment]
@lithiumpie this is _awesome_ — you are _awesome_!  Do you want to go ahead with a merge or would you like to handle your lost commit?

> I don't know why this PR includes my last commit

**Comment by lithiumpie** [comment]
If the history will not become an issue, just merge it after reviewing :smiley:

**Comment by zillou** [comment]
@lithiumpie I reviewed your updates. They are greate to go,  please feel free to merge and 🐑 them.

**Comment by doomspork** [comment]
Thank you again @lithiumpie and @zillou 💪

**Pull request merged**
