### PR TITLE
[UK] Bump pattern matching to 1.0.2

### PR DESCRIPTION
**Pull request by brain-geek**

### CODE REVIEW

**Comment by brain-geek** [comment]
Hey @doroshenkoss , could you check this small change? As well as #1572 , which is also small. Unfortunately, my Ukrainian is a bit rusty.
Thanks!

**Comment by doomspork** [comment]
@brain-geek if you and @doroshenkoss are interested, I could setup a team for you both (and others) to tag these translations in the future.

**Comment by brain-geek** [comment]
@doroshenkoss Hey, what do you think about being in Ukrainian translators team, by the way? 😄

**Comment by doroshenkoss** [comment]
@doomspork @brain-geek I'm in the game)

**Comment by doomspork** [comment]
@brain-geek & @doroshenkoss consider it done!  The new @elixirschool/ukrainian  team has been created.  Let me know if there's anything I need to change.

**Pull request merged**
