### PR TITLE
Update enum.md

### PR DESCRIPTION
**Pull request by StefanoChiodino**
Rephrase sentence that sounded odd. Not sure about the mention of documentation, so I shortened it too.

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @StefanoChiodino! @tajchumber thoughts on bumping the version for this? Is this a change we want translated?

**Comment by StefanoChiodino** [comment]
Had a look at the Italian translation and besides sounding very mechanical it has the same structure.

**Comment by StefanoChiodino** [comment]
Believe it or not despite being my native language it takes me twice as long :D

I'll give it a go!

**Comment by StefanoChiodino** [comment]
I've done what I could in Italian. Sounds a bit better to me now and it doesn't have the original problem of mentioning documentation that wasn't actually discussed above.

**Comment by tajchumber** [comment]
@StefanoChiodino don't worry about other translations in this PR :)
For this pull request, just bump the version at the top and we will merge!

**Comment by StefanoChiodino** [comment]
Good now?

**Comment by tajchumber** [comment]
thanks @StefanoChiodino

**Comment by doomspork** [comment]
Thank you @StefanoChiodino and @tajchumber 💜

**Pull request merged**
