### PR TITLE
Fix broken link on the "Instrumenting Phoenix with Telemetry and LiveDashboard" blog post

### PR DESCRIPTION
**Pull request by jordelver**
Link was broken due to malformed Markdown

### CODE REVIEW

**Comment by jordelver** [comment]
@SophieDeBenedetto letting you know about this :)

**Comment by doomspork** [comment]
Thank you @jordelver!

**Comment by jordelver** [comment]
Wow. That was quick! 😆

**Comment by doomspork** [comment]
Perfect timing! I opened GitHub and there your PR was :tada: 

Have a great week @jordelver

**Comment by jordelver** [comment]
And you!

**Comment by doomspork** [comment]
By the way! Part 2 https://github.com/elixirschool/elixirschool/pull/2284 is ready for review if you'd like to give it a read through and provide feedback.

**Comment by jordelver** [comment]
I've left some feedback @doomspork 👍

**Comment by jordelver** [comment]
Oh, and I fixed a couple of things on Part 1 (which I hadn't read yet!)

https://github.com/elixirschool/elixirschool/pull/2298

**Comment by doomspork** [comment]
Thank you @jordelver :pray:

**Pull request merged**
