### PR TITLE
[PT] Update pt/lessons/basics/functions.md to 1.2.0

### PR DESCRIPTION
**Pull request by herminiotorres**

### CODE REVIEW

**Comment by herminiotorres** [comment]
@vbrazo you could review my pull-request? :heart:

**Comment by anderkonzen** [comment]
Hi @herminiotorres ! Just to confirm: have you checked the original English version to see if there were changes? Your commit just updates the version reference, is that correct?

**Comment by herminiotorres** [comment]
@anderkonzen I compared with the english version, but feel free to look it too

**Comment by doomspork** [comment]
@anderkonzen are you happy to merge?

**Comment by anderkonzen** [comment]
@doomspork yep, sounds good!

**Comment by herminiotorres** [comment]
@anderkonzen @anderkonzen thank you guys made a good stuff to learn elixir <3

**Pull request merged**
