### PR TITLE
Add link rel canonical

### PR DESCRIPTION
**Pull request by lex111**
According to https://support.google.com/webmasters/answer/139066?hl=en

### CODE REVIEW

**Comment by doomspork** [comment]
@lex111 you're the man with a plan! I need to level up my SEO skills, any suggestions on where I could do that?

**Comment by lex111** [comment]
@doomspork ha ha, I'm glad to hear that, but in fact, SEO is already good! Seems to me we need to improve the print version.

P.S. Found one "bug", why is the `gr` prefix used for the Greek translation, when should there be an `el` (see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)?

**Comment by lex111** [comment]
Oh, that's right! https://en.wikipedia.org/wiki/ISO_3166-1

However, for `hreflang` attribute we need to use the language code according to ISO 639, that is: `el`!

**Comment by lex111** [comment]
Quick fix! https://github.com/elixirschool/elixirschool/pull/1809

**Comment by gemantzu** [comment]
@lex111 you are asking the ancient questions here man, the cannon name for our country is Hellas, we call it Hellada (from our own Ελλάδα), but our annointed name `Greece` and we as `Greeks` from the ancient times seem to be stuck with us [check here](https://en.wikipedia.org/wiki/Name_of_Greece). The cannonical abbreviation should always be 'el', but these things are tough to change all over the place.

**Pull request merged**
