### PR TITLE
Update otp-supervisors.md

### PR DESCRIPTION
**Pull request by sebastiannicklas**
Update German translation to mirror English version: add Child Specification and DynamicSupervisor

### CODE REVIEW

**Comment by doomspork** [comment]
Howdy @sebastiannicklas! Do we need to change the version at the top of the file to match the english version? Those versions are used for the Translation Report, if you haven't seen it: https://elixirschool.com/de/report/

**Comment by sebastiannicklas** [comment]
Hi @doomspork! Oh, I haven't seen the Translation Report. 
The German translation matches the English one now, so, yes, I think we should update the version in the file.

**Comment by sebastiannicklas** [comment]
Please see https://github.com/elixirschool/elixirschool/pull/2101

**Comment by sebastiannicklas** [comment]
I closed this PR because I made another PR with the complete changes.

**Pull request closed without merging**
