### PR TITLE
Update functions.md

### PR DESCRIPTION
**Pull request by quentusrex**
Fixed typo in error output

### CODE REVIEW

**Comment by lex111** [comment]
@doomspork wait, but shouldn't we fix this in the appropriate translation files?

**Comment by doomspork** [comment]
@lex111 yes sir, that's preferable. In this case (or the event the PR author doesn't have time to do it), we can just do a follow-up PR with those changes.

I can do that or you can 😁

**Comment by lex111** [comment]
@doomspork stay back, I'll do it! :smiley:

**Comment by doomspork** [comment]
Thank you again @quentusrex, @tajchumber, and @lex111 😁

**Pull request merged**
