### PR TITLE
Say hello to Appendix, and more!

### PR DESCRIPTION
**Pull request by burden**
## Summary
* updated theme paying homage to the original purple theme
* introducing Appendix!
* index.md has a new layout called `home`
* index.md needs `features` when `home` layout is in use
* index.md falls back to `page` layout gracefully
* added `exclude_from_chapters` parameter to `_config.yml`
  * this tells the plugin to skip pages that are not chapters (i.e. appendix)
* added `disable_transform` to locale file (default: false)
  * setting to `true` will disable the use of uppercase letters in the menu and buttons

## Responsive layout

**Big screens**

screen shot 2018-03-27 at 1 24 36 am

**Small screen (Landscape)**
screen shot 2018-03-27 at 1 24 36 am

**Small screen (Portrait)**
screen shot 2018-03-27 at 1 24 36 am

## Appendix
**Front Matter**
```yaml
title: Published title of article
preview: image.jpg
pinned: true|false
```
**Notes**
* save articles in `_posts/` 
* save preview images in `_assets/images`
screen shot 2018-03-27 at 1 43 18 am

screen shot 2018-03-27 at 1 40 07 am

screen shot 2018-03-27 at 1 48 32 am

### CODE REVIEW

**Comment by eksperimental** [comment]
Looks AWESOME

**Comment by doomspork** [comment]
Thank you thank you thank you @burden!  I will go through this today and tomorrow and let you know if there's any feedback.

I'll also get started on some blog posts 🕺

**Comment by eksperimental** [comment]
I would remove the :cn language sample code from the front page as :cn is not a valid ISO code for Chinese languages. It is zh. I will open up an issue.

**Comment by eksperimental** [comment]
I think it is a bit too much having the html5up licence note on every file. It looks like the old bsd license (was it that one that had tonbe included in every single file?) I have checked the cc license and it just required to give credit, which can be done in the readme file or we can create a credits page for such purpose.

**Comment by doomspork** [comment]
Thank you for all the wonderful feedback @eksperimental, you're so awesome!

**Comment by pjhampton** [comment]
This looks amazing! :heart:

**Comment by gemantzu** [comment]
Sorry for being late, here are my 2 cents:
- A little too white for my eyes but very clean and nice layout. I like very much the fact that the languages are on top left.
- On chrome 65 the scrolldown was acting a little funny, it scrolled until 20% and then I had to click on the page to continue scrolling. This did not happen on Firefox (for exact versions you will have to wait till I get home).
- I think if it is possible it will be better if the side panel will scroll independently from the main page, not alongside it.
- The versioning system is gone, we should bring it back.
I will test it more on the afternoon and report back if I see anything else.

**Comment by doomspork** [comment]
Good catch on the versioning plugin @gemantzu!  @burden and I will take a peek at getting that wired back up

**Comment by burden** [comment]
I just double checked that versioning was working. See screenshot below.
screen shot 2018-04-16 at 12 56 25 pm

@gemantzu I could have totally overlooked something. Was there anything in particular that was not working for you?

**Comment by gemantzu** [comment]
@burden Not sure, I will take a look at it when I return home on Sunday. I checked a few pages and it was not showing up.

**Comment by gemantzu** [comment]
So, I am back. Unfortunately, I forgot I had to do this and already updated my browser before testing again. It might be my setup though, because I keep getting weird browsing experience from the same code. I can see the versioning now, but I can also see the following [weird thing](https://ibb.co/mZxCtc), which only happens on greek language (all the others work ok). I will fetch now latest commits and check again.

**Comment by doomspork** [comment]
Closing for #1392

**Comment by nscyclone** [comment]
Apologies for coming late to the party! Thanks a lot @burden, that was a huge amount of good work!
Everything looks amazing but I 've got several minor things to be clarified/improved:
* There are some unused `_includes`: e.g. `section-sidebar-appendix` and `section-sidebar-latest`. Are there any further plans on those?
* [`H1` headers seem too big](https://user-images.githubusercontent.com/5345029/39238545-2e2dda9c-4887-11e8-9458-0e495f168eea.png), WDYT about decreasing their size a little?
* In my opinion, `contributors` section [takes a lot of unused space](https://user-images.githubusercontent.com/5345029/39238440-e66fd606-4886-11e8-8229-1c626a7668db.png).
* Opening `appendix` index or post changes the current language to English, is this a desired behaviour?
* [Color contrast for the main text parts](https://user-images.githubusercontent.com/5345029/39239166-be92b8e0-4888-11e8-861f-ba1e41fbb487.png) might need some attention.

**Comment by eksperimental** [comment]
My main concern is the color contrast and maybe the font size. I was trying to read it for a while and my eyes were hurting

**Comment by doomspork** [comment]
@eksperimental / @nscyclone this is all great feedback!  @burden offered to help us incorporate feedback over the next few weeks so this is a wonderful start

**Pull request closed without merging**
