### PR TITLE
Formatting the code with the Elixir format tool

### PR DESCRIPTION
**Pull request by SpyR1014**
To celebrate the Elixir formatter I've gone through and formatted the code blocks. The example code will now reflect the formatted Elixir of the future!

I specifically ignored some of the examples because the format was important for teaching purposes and only formatted code blocks and config.

I also found a breaking syntax error in the [Guardian token response example](https://github.com/elixirschool/elixirschool/compare/master...SpyR1014:master#diff-905f78632ecd759996eb649fac036c65R245) where `{token: jwt}` needed to be changed to `%{token: jwt}`.

There was also a broken [ecto example](https://github.com/elixirschool/elixirschool/compare/master...SpyR1014:master#diff-4955bc2f9bc2a2d8f301f1425c2c34feR274) that was missing a comma.

Something very interesting the formatter did was add more parenthesis. This is especially prevalent in the plugs and ecto section.

### CODE REVIEW

**Comment by SpyR1014** [comment]
Thank you for creating such a brilliant learning resource for the Elixir community.

I understand if formatting everything is too much so I don't mind closing this if that's the case.

**Comment by doomspork** [comment]
@SpyR1014 this is _awesome_!  I'm going to go through this and make sure everything looks good 👍

**Comment by doomspork** [comment]
@SpyR1014 would you be willing to apply these changes to _all_ the lessons (including translations)?  😁

**Comment by SpyR1014** [comment]
@doomspork Thank you! I can definitely work towards making these changes in all the languages. 😄 

Do you want me to continue in this pull request or would you like to break it up into language chunks?
I look forward to hearing your comments. I think I've formatted all the lessons in English except for maybe a benchee code block or two.

I also haven't formatted the iex code because it usually doesn't need formatting.

**Comment by doomspork** [comment]
@SpyR1014 we can merge this and then apply the change to all of the other languages (it should be the same code, just needs to be copied to them).

I think we'll want to bump the patch version on these lessons.  What do you think @nscyclone?  If we bump the minor version it could throw off actual translations.

**Comment by SpyR1014** [comment]
@doomspork Sounds great!

**Comment by nscyclone** [comment]
Thanks @SpyR1014!
@doomspork that sounds like a good idea for me.

**Comment by SpyR1014** [comment]
@doomspork Patches applies! 😃

**Pull request merged**
