### PR TITLE
[pt] Fixes in pt/lessons/ecto/basics.md

### PR DESCRIPTION
**Pull request by vbrazo**

### CODE REVIEW

**Comment by vbrazo** [comment]
@anderkonzen anytime. I'll see if I can find other ways to contribute here. 
Thanks for your reviews 👍

**Comment by vbrazo** [comment]
@anderkonzen 🇧🇷

**Comment by anderkonzen** [comment]
@vbrazo Btw, are you double checking if the pt-br version matches the latest en? I believe we may have some lessons that are not in sync with the en... If you have some spare time to review this point too it would be awesome!

**Comment by vbrazo** [comment]
@anderkonzen I'll see if I can find some extra time to do the double check over the next days. Thanks for letting me know 👍

**Pull request merged**
