### PR TITLE
Fix instructions on path to save verify_request.ex

### PR DESCRIPTION
**Pull request by gjastrab**
Path was missing top level namespace folder of the application.

### CODE REVIEW

**Comment by gjastrab** [comment]
Certainly, a few of the versions were only `0.9.x` so I bumped those to `0.10.0`

**Comment by doomspork** [comment]
Thank you @gjastrab 👍

**Comment by gjastrab** [comment]
No sweat, thanks for your work on elixir school, I've found it a great resource!

**Comment by doomspork** [comment]
You're very welcome @gjastrab!  We're always open to feedback on how to make it even better 😁

**Pull request merged**
