### PR TITLE
Elixir format the rest of the lessons

### PR DESCRIPTION
**Pull request by SpyR1014**
This pull request ~~currently only partially~~ addresses issue #1251.

I'm trying to keep each language track in a separate commit.
I'll continue adding to it until they're all done.

### CODE REVIEW

**Comment by SpyR1014** [comment]
I tried to keep this as a separate change from the english formatted version and I got my git tied up in a knot.

Are the reverts for this pull request a problem? (Sorry! This is my first real open source contribution)

**Comment by doomspork** [comment]
@SpyR1014 this is great and the reverts shouldn't be an issue.  I'll look this over and see if there's any changes we need 👍

**Comment by SpyR1014** [comment]
@doomspork I believe it's all done! :)

**Comment by SpyR1014** [comment]
I'll go through and resolve the conflicts as well whoops!

**Comment by doomspork** [comment]
Sadly @SpyR1014 I can't `Rebase and Merge` due to conflicts so I'll have to squash, sorry about that :(

**Comment by SpyR1014** [comment]
@doomspork It's been an absolute pleasure! My twitter handle is @spyr1014. Thank you for such a great 🦄resource🦄! 😃❤️

**Pull request merged**
