### PR TITLE
[TA] Initial Tamil translation

### PR DESCRIPTION
**Pull request by kalarani**
Initial setup for Tamil lessons and translation of `basics` lesson.

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you and welcome @kalarani, this is _tremendous_! Thanks again for getting involved.  My apologizes for the Wiki guide getting out to date for translations 😰 

Would you mind adding a `ta` file to this directory: https://github.com/elixirschool/elixirschool/tree/master/_data/locales

As well as update this one:
https://github.com/elixirschool/elixirschool/blob/master/_data/interlang.yml

Thank you again 😁

**Comment by kalarani** [comment]
Welcome @doomspork !

I've added `ta.yml` and updated the `interlang.yml`. Let me know if I'm missing something.

**Comment by doomspork** [comment]
@nscyclone this should be everything to kick off a new translation, correct?  I've lost track of the changes need to make

**Comment by nscyclone** [comment]
@doomspork I think so. Even I myself forgot about it when was adding arabic translation (should be fixed in #1200).  Thanks!

**Comment by doomspork** [comment]
Thank you again @kalarani!!

**Pull request merged**
