### PR TITLE
[GR] Update gr/lessons/basics/functions.md to 1.2.0

### PR DESCRIPTION
**Pull request by Kosmas**

### CODE REVIEW

**Comment by gemantzu** [comment]
@Kosmas thanks again for the PR. Do you mind if we let @RTSolo incorporate your changes into his PR? He has translated the examples as well, and it makes sense for ES to have equivalent examples on all translations for mass changes.

**Comment by Kosmas** [comment]
Yes, that is absolutely fine @gemantzu. @RTSolo please go ahead and close this one.

**Comment by RTSolo** [comment]
Thanks @Kosmas , it should be ok now.

**Comment by gemantzu** [comment]
Both of you, thanks. #2466 has been approved. I went on and added the label `hacktoberfest-approved` to this one since  the work was incorporated into #2466.

**Pull request closed without merging**
