### PR TITLE
[TR]  Remove the "redirect_from" directive from all.

### PR DESCRIPTION
**Pull request by yasinyaman**
@eksperimental , all removed.

### CODE REVIEW

**Comment by eksperimental** [comment]
can you rebase against master and add the latest commit
also that commit is adding tr/lessons/advanced/metaprogramming.md

**Comment by eksperimental** [comment]
you need to base your work on `master`, you are submitting 24 additional commits that got squashed into 1, when your contributions were merged.

**Comment by yasinyaman** [comment]
@eksperimental  How to do this ?    @MertcanGokgoz

**Comment by eksperimental** [comment]
Sorry, but it looks like big mess, because now you are adding more commits.
My suggestion is:
1. never work on master, create a new branch for example named "remove_redirect_from"
2. start over, pull the latest copy of master, and create a new branch
3. remove the "redirect_from" directive from ever file in the `tr` dir
4. make sure you only have the changes involving this new PR.
5. commit and push
6. create a new PR

**Comment by eksperimental** [comment]
Closing in favour of #1403

**Pull request closed without merging**
